# 1/17/21

# Default options according to https://prettier.io/docs/en/options.html

# Commonly used options -
# printWidth: 80
# tabWidth: 2
# useTabs: false
# semi: true
# singleQuote: false
# quoteProps: "as-needed"
# jsxSingleQuote: false
# trailingComma: "es5"
# bracketSpacing: true # for objects
# jsxBracketSameLine: false
# arrowParens: "always"

# Note that Prettier will not change to or from ``
# ESLint potentially can via "@typescript-eslint/quotes" rule

# Esoteric and/or options intended for CLI -
# rangeStart: 0
# rangeEnd:
# parser:
# filepath:
# requirePragma: false
# insertPragma: false

# Line wrapping options -
# proseWrap: "preserve" # for markdown
# htmlWhitespaceSensitivity: "css"
# vueIndentScriptAndStyle: false
# endOfLine: "lf"

# Mixing languages -
# embeddedLanguageFormatting: "auto"

# My Customizations

# Prettier will reformat multiple lines into one in some cases,
#   which works poorly with a long line length ("printWidth").
#   I still find the default 80 is too short though.
printWidth: 90

# I prefer typing fewer characters by omitting semicolons.
semi: false
